apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  labels:
    app: getting-started
spec:
  capacity:
    storage: 20Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: gp3 
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-086790921432698b6    
    fsType: ext4
